trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'test-libmnl:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: mkdir -p bin; docker run --rm --entrypoint cat $(imageName) /bin/nltest > bin/nltest
  displayName: 'copy binary'

- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@19
  displayName: 'WhiteSource Bolt'
  inputs:
    cwd: './bin'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'nltest'
    targetPath: './bin'
