trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'test-libmnl:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: |
    mkdir -p bin
    docker run --rm --entrypoint cat $(imageName) /bin/nltest > bin/nltest
    tar cfJ "$BUILD_ARTIFACTSTAGINGDIRECTORY/release.tar.xz" "./bin"
  displayName: 'copy binary'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/release.tar.xz'
