trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'test-libmnl:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker run --rm --entrypoint cat $(imageName) /bin/nltest > nltest
  displayName: 'copy binary'
  
