trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'test-libmnl:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: |
    mkdir -p bin
    docker create --name test $(imageName)
    docker cp test:/deps bin
    docker cp test:/bin/nltest bin
  displayName: 'copy binary'

- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@19
  displayName: 'WhiteSource Bolt'
  inputs:
    cwd: './bin'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'nltest'
    targetPath: './bin'
